# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Mus't be unique within a project.
name: "lnclass_app"

# The runtime the application uses.
type: "ruby:2.7.2"

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    postgresdatabase: 'dbpostgres:postgresql'


# The size of the persistent disk of the application (in MB).
disk: 5120

# Set environment variables to adjust how Rails will run.
variables:
    env:
        RAILS_ENV: 'production'
        RAILS_LOG_TO_STDOUT: true
        BUNDLE_ERROR_ON_STDERR: 1
        RAILS_TMP: /tmp
        EXECJS_RUNTIME: 'Node'
#Define the web locations your application is using:

web:
  upstream: 
    socket_family: "unix"
  commands: 
    start: "\"unicorn -l $SOCKET -E production config.ru\""
  locations: 
    '/': 
      root: "\"public\""
      passthru: true
      expires: "1h"
      allow: true
# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
  'web/uploads':
    source: local
    source_path: uploads

 
# The hooks executed at various points in the lifecycle of the application.

hooks:
    # The build hook turns what is in source control into the deployable application.
    build: |
      bundle install --without development test
    deploy: |
      RACK_ENV=production bundle exec rake db:migrate
    # The deploy hook runs after your application has been deployed and started.

# The configuration of the application when running.
web:
    upstream:
        # Send requests to the app server through a unix socket, whose location
        # will be defined in an environment variable named SOCKET.
        socket_family: "unix"

    commands:
        start: "bundle exec unicorn -l $SOCKET -E production config.ru"

        